# Generated by Django 5.2.7 on 2025-11-01 09:25

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import timezone_field.fields
import users.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Введите фамилию', max_length=150, verbose_name='Фамилия')),
                ('age', models.PositiveSmallIntegerField(help_text='Введите возраст', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст')),
                ('email', models.EmailField(help_text='Введите email', max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите номер телефона', max_length=128, region=None, verbose_name='Телефон')),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, help_text='Для корректного отображения расписаний сессий', null=True, verbose_name='Часовой пояс')),
                ('is_staff', models.BooleanField(default=False, help_text='Административный доступ', verbose_name='Персонал?')),
                ('is_active', models.BooleanField(default=False, help_text='Аккаунт активен', verbose_name='Активный?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('country', django_countries.fields.CountryField(help_text='Выберите страну учебного заведения', max_length=2, verbose_name='Страна')),
                ('institution', models.CharField(help_text='Укажите название учебного учреждения', max_length=255, verbose_name='Учебное учреждение')),
                ('degree', models.CharField(help_text='Например: Бакалавр, Магистр, Специалист, Сертификат', max_length=255, verbose_name='Ученая степень / квалификация')),
                ('specialisation', models.CharField(help_text='Специализация или программа обучения', max_length=255, verbose_name='Специализация / направление')),
                ('year_start', models.PositiveSmallIntegerField(help_text='Укажите год начала обучения', validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='Год начала обучения')),
                ('year_end', models.PositiveSmallIntegerField(blank=True, help_text='Укажите год окончания обучения или оставьте пустым, если обучение в процессе', null=True, validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='Год окончания обучения')),
                ('document', models.FileField(blank=True, help_text='Прикрепите скан диплома/сертификата', null=True, upload_to='education_docs/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), users.validators.validate_file_size], verbose_name='Скан диплома/сертификата')),
                ('is_verified', models.BooleanField(default=False, help_text='Флаг модерации подлинности (проверяется администратором)', verbose_name='Верификация')),
                ('creator', models.ForeignKey(blank=True, help_text='Укажите пользователя, создавшего запись', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_educations', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
                'ordering': ['country', 'institution', 'specialisation'],
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Укажите название метода', max_length=255, unique=True, verbose_name='Название метода')),
                ('description', models.TextField(help_text='Укажите описание метода', verbose_name='Описание метода')),
                ('slug', models.SlugField(blank=True, help_text='Укажите slug-название метода', max_length=255, unique=True, verbose_name='Slug-название метода')),
                ('creator', models.ForeignKey(blank=True, help_text='Укажите пользователя, создавшего запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_methods', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Метод',
                'verbose_name_plural': 'Методы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Укажите название специализации', max_length=255, unique=True, verbose_name='Название специализации')),
                ('description', models.TextField(help_text='Укажите описание специализации', verbose_name='Описание специализации')),
                ('slug', models.SlugField(blank=True, help_text='Укажите slug-название специализации', max_length=255, unique=True, verbose_name='Slug-название специализации')),
                ('creator', models.ForeignKey(blank=True, help_text='Укажите пользователя, создавшего запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_specialisations', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.CharField(help_text='Укажите роль пользователя', max_length=50, unique=True, verbose_name='Роль пользователя')),
                ('creator', models.ForeignKey(blank=True, help_text='Укажите пользователя, создавшего запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['role'],
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Укажите роль пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userrole', verbose_name='Роль пользователя'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('type', models.CharField(help_text='Укажите вид запроса', max_length=100, verbose_name='Вид запроса')),
                ('name', models.CharField(help_text='Укажите название запроса', max_length=255, verbose_name='Название запроса')),
                ('slug', models.SlugField(blank=True, help_text='Укажите slug-название запроса', max_length=255, null=True, unique=True, verbose_name='Slug-название запроса')),
                ('creator', models.ForeignKey(blank=True, help_text='Укажите пользователя, создавшего запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['type', 'name'],
                'unique_together': {('type', 'name')},
            },
        ),
    ]
