# Generated by Django 5.2.7 on 2025-11-02 10:09

import django.core.validators
import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('therapy_experience', models.BooleanField(default=False, help_text='Был ли у вас опыт терапии?', verbose_name='Опыт терапии')),
                ('preferred_methods', models.ManyToManyField(blank=True, help_text='Методы или подходы, которые вам близки', related_name='method_clients', to='users.method', verbose_name='Предпочтительные методы')),
                ('requested_topics', models.ManyToManyField(blank=True, help_text='Темы, с которыми вы хотите работать', related_name='topic_clients', to='users.topic', verbose_name='Запросы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_verified', models.BooleanField(default=False, help_text='Флаг модерации подлинности (проверяется администратором)', verbose_name='Верификация пользователя')),
                ('gender', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], help_text='Укажите пол', verbose_name='Пол')),
                ('is_all_education_verified', models.BooleanField(default=False, help_text='Флаг модерации подлинности (проверяется администратором)', verbose_name='Верификация образования')),
                ('biography', models.TextField(blank=True, help_text='Добавьте информацию о себе', null=True, verbose_name='О специалисте')),
                ('photo', models.ImageField(blank=True, help_text='Добавьте фотографию вашего профиля', null=True, upload_to='photo/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), users.validators.validate_file_size], verbose_name='Фотография профиля')),
                ('work_experience', models.PositiveSmallIntegerField(blank=True, help_text='Укажите текущий опыт работы (лет)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Опыт')),
                ('languages', models.CharField(choices=[('english', 'английский'), ('russian', 'русский')], default='russian', help_text='Укажите возможный язык для проведения сессий', verbose_name='Язык')),
                ('therapy_format', models.CharField(choices=[('online', 'удаленно'), ('offline', 'встреча')], default='online', help_text='Укажите возможны формат для проведения сессий', verbose_name='Формат сессии')),
                ('price_individual', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите стоимость индивидуальной сессии (руб.)', max_digits=10, verbose_name='Стоимость индивидуальной сессии (руб.)')),
                ('price_couples', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите стоимость парной сессии (руб.)', max_digits=10, verbose_name='Стоимость парной сессии (руб.)')),
                ('work_status', models.CharField(choices=[('working', 'работает'), ('not_working', 'не работает')], default='working', help_text='Текущий рабочий статус психолога', verbose_name='Рабочий статус')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Рейтинг психолога', max_digits=3, verbose_name='Рейтинг')),
                ('educations', models.ManyToManyField(blank=True, help_text='Добавьте образование', related_name='education_psychologists', to='users.education', verbose_name='Образование')),
                ('methods', models.ManyToManyField(blank=True, help_text='Добавьте методы (инструмент/подход)', related_name='method_psychologists', to='users.method', verbose_name='Метод')),
                ('specialisations', models.ManyToManyField(blank=True, help_text='Добавьте специализацию (методологическая школа)', related_name='specialisation_psychologists', to='users.specialisation', verbose_name='Специализация')),
                ('topics', models.ManyToManyField(blank=True, help_text='Добавьте тему/вопрос (запрос на терапию)', related_name='topic_psychologists', to='users.topic', verbose_name='Запрос')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Психолог',
                'verbose_name_plural': 'Психологи',
                'ordering': ['user__email'],
            },
        ),
    ]
