# Generated by Django 5.2.7 on 2025-11-02 21:17

import django.contrib.postgres.fields
from django.db import migrations, models

import users.services.defaults


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientprofile_psychologistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('english', 'английский'), ('russian', 'русский')], max_length=50), default=users.services.defaults.default_languages, help_text='Укажите языки, на которых можно проводить сессии', size=None, verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='therapy_format',
            field=models.CharField(choices=[('online', 'удаленно'), ('offline', 'встреча'), ('any', 'любая')], default='online', help_text='Укажите возможны формат для проведения сессий', verbose_name='Формат сессии'),
        ),
    ]
