# Generated by Django 5.2.7 on 2025-11-03 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Введите возраст', null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст'),
        ),
    ]
