# Generated by Django 5.2.7 on 2025-11-04 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_appuser_age'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topic',
            name='group_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Укажите название группы запроса', max_length=100, verbose_name='Группа запросов'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('type', 'group_name', 'name')},
        ),
    ]
