# Generated by Django 5.2.7 on 2025-11-10 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_topic_unique_together_topic_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=19, help_text='Введите возраст', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
