# Generated by Django 5.2.7 on 2025-12-05 21:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_remove_psychologistprofile_educations'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='has_preference',
            field=models.BooleanField(default=False, help_text='Есть ли личные предпочтения', verbose_name='Наличие предпочтений'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_ps_age',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('<25', 'До 25 лет'), ('25-35', '25-35 лет'), ('35-45', '35-45 лет'), ('45-55', '45-55 лет'), ('>55', 'От 55 лет')], max_length=10), blank=True, default=list, help_text='Укажите предпочитаемый возраст психолога', size=None, verbose_name='Предпочитаемый возраст психолога'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_ps_gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], max_length=10), blank=True, default=list, help_text='Укажите предпочитаемый пол психолога', size=None, verbose_name='Предпочитаемый пол психолога'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['age'], name='idx_user_age'),
        ),
        migrations.AddIndex(
            model_name='psychologistprofile',
            index=models.Index(fields=['gender'], name='idx_ps_gender'),
        ),
    ]
