# Generated by Django 5.2.7 on 2025-12-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_clientprofile_has_preference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='has_preference',
            new_name='has_preferences',
        ),
    ]
