# Generated by Django 5.2.7 on 2025-12-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_has_preference_clientprofile_has_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_topic_type',
            field=models.CharField(choices=[('individual', 'Индивидуальная'), ('couple', 'Парная')], default='individual', help_text='Укажите интересующий вид консультации', max_length=20, verbose_name='Вид консультации'),
        ),
    ]
