# Generated by Django 5.2.7 on 2025-12-17 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_clientprofile_preferred_topic_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='practice_start_year',
            field=models.PositiveSmallIntegerField(default=2000, help_text='Укажите год начала практики', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год начала практики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='price_currency',
            field=models.CharField(default='RUB', help_text='Укажите валюту', max_length=3, verbose_name='Валюта сессии'),
        ),
    ]
