# Generated by Django 5.2.7 on 2025-12-18 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_psychologistprofile_work_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistprofile',
            name='practice_start_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Укажите год начала практики', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год начала практики'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='price_currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('KZT', 'Казахстанский тенге')], default='RUB', help_text='Укажите валюту', max_length=3, verbose_name='Валюта сессии'),
        ),
    ]
