# Generated by Django 5.2.7 on 2026-01-09 11:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_psychologistprofile_practice_start_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='has_time_preferences',
            field=models.BooleanField(default=False, help_text='Есть ли личные предпочтения по времени сессии', verbose_name='Наличие предпочтения по времени сессии'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, help_text='Выбор клиентом предпочитаемых временных слотов для сессии с учетом UTC', size=None, verbose_name='Предпочитаемые временные слоты для сессии'),
        ),
    ]
