# Generated by Django 5.2.7 on 2026-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_clientprofile_has_time_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите slug-полное имя психолога', max_length=255, null=True, unique=True, verbose_name='Slug-полное имя'),
        ),
    ]
