# Generated by Django 5.2.7 on 2026-03-25 19:55

import django.contrib.postgres.fields
from django.db import migrations, models

import users.services.defaults


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_psychologistprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='preferred_ps_gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10), blank=True, default=list, help_text='Укажите предпочитаемый пол психолога', size=None, verbose_name='Предпочитаемый пол психолога'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], help_text='Укажите пол', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('english', 'Английский'), ('russian', 'Русский')], max_length=50), default=users.services.defaults.default_languages, help_text='Укажите языки, на которых можно проводить сессии', size=None, verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='therapy_format',
            field=models.CharField(choices=[('online', 'Онлайн встреча'), ('offline', 'Личная встреча'), ('any', 'Любая')], default='online', help_text='Укажите возможны формат для проведения сессий', verbose_name='Формат сессии'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='work_status',
            field=models.CharField(choices=[('working', 'Работает'), ('not_working', 'Не работает')], default='working', help_text='Текущий рабочий статус психолога', verbose_name='Рабочий статус'),
        ),
    ]
