# Generated by Django 5.2.7 on 2026-04-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_clientprofile_preferred_ps_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistprofile',
            name='price_couples',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Укажите стоимость парной сессии', max_digits=10, verbose_name='Стоимость парной сессии'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='price_individual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Укажите стоимость индивидуальной сессии', max_digits=10, verbose_name='Стоимость индивидуальной сессии'),
        ),
    ]
