# Generated by Django 5.2.7 on 2025-12-30 15:06

import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.db.models.deletion
import timezone_field.fields
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, help_text='Для корректного применения правила в календаре пользователя', null=True, verbose_name='Часовой пояс')),
                ('rule_start', models.DateField(help_text='Укажите дату старта правила', verbose_name='Дата старта правила')),
                ('rule_end', models.DateField(blank=True, help_text='Укажите дату окончания правила', null=True, verbose_name='Дата окончания правила')),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), help_text='Укажите рабочие дни недели', size=None, verbose_name='Рабочие дни недели')),
                ('start_time', models.TimeField(help_text='Укажите начало рабочего дня', verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(help_text='Укажите окончание рабочего дня', verbose_name='Окончание рабочего дня')),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=60, help_text='Укажите продолжительность 1 слота', verbose_name='Продолжительность 1 слота')),
                ('break_minutes', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Укажите перерыв между сессиями', null=True, verbose_name='Перерыв между сессиями')),
                ('is_active', models.BooleanField(default=True, help_text='Флаг действия правила', verbose_name='Признак действия правила')),
                ('owner', models.ForeignKey(help_text='Укажите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Правило доступности специалиста',
                'verbose_name_plural': 'Правила доступности специалиста',
                'ordering': ['pk', 'owner', 'rule_start'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('exception_start', models.DateField(help_text='Укажите дату старта исключения', verbose_name='Дата старта исключения')),
                ('exception_end', models.DateField(help_text='Укажите дату окончания исключения', verbose_name='Дата окончания исключения')),
                ('start_time', models.TimeField(blank=True, help_text='Укажите время начала исключения', null=True, verbose_name='Время начала исключения')),
                ('end_time', models.TimeField(blank=True, help_text='Укажите время окончания исключения', null=True, verbose_name='Время окончания исключения')),
                ('reason', models.CharField(blank=True, choices=[('day_off', 'Выходной'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный')], help_text='Укажите причину исключения', max_length=32, null=True, verbose_name='Причина исключения')),
                ('global_availability', models.CharField(choices=[('available', 'Доступный'), ('unavailable', 'Недоступный')], default='available', help_text='Укажите значение для глобальной доступности (available / unavailable)', verbose_name='Глобальная доступность (available / unavailable)')),
                ('owner', models.ForeignKey(help_text='Укажите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('rule', models.ForeignKey(blank=True, help_text='Укажите правило для которого устанавливается исключение', null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_engine.availabilityrule', verbose_name='Правило для которого устанавливается исключение')),
            ],
            options={
                'verbose_name': 'Исключение из правил доступности',
                'verbose_name_plural': 'Исключения из правил доступности',
                'ordering': ['pk', 'owner', 'exception_start'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Укажите название события', max_length=255, verbose_name='Название события')),
                ('description', models.TextField(blank=True, help_text='Укажите описание события', null=True, verbose_name='Описание события')),
                ('event_type', models.CharField(choices=[('event', 'Встреча'), ('group_event', 'Группа встреч')], default='event', help_text='Укажите тип события', max_length=32, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланировано'), ('started', 'Начато'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('archived', 'Архивировано')], default='draft', help_text='Укажите статус события', max_length=32, verbose_name='Статус события')),
                ('cancel_reason', models.TextField(blank=True, help_text='Укажите причину отмены события', null=True, verbose_name='Причина отмены события')),
                ('visibility', models.CharField(choices=[('private', 'Приватная'), ('public', 'Публичная')], default='private', help_text='Укажите видимость события', max_length=32, verbose_name='Видимость события')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Укажите максимально допустимое количество участников в групповом событии', null=True, verbose_name='Максимально допустимое количество участников в групповом событии')),
                ('is_recurring', models.BooleanField(default=False, help_text='Флаг повторяющегося события', verbose_name='Повторяющееся события')),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('google', 'Google Calendar'), ('apple', 'Apple Calendar'), ('outlook', 'Outlook')], default='internal', help_text='Укажите источник события', max_length=32, verbose_name='Источник события')),
                ('external_id', models.CharField(blank=True, help_text='Укажите ID события во внешнем календаре', max_length=255, null=True, verbose_name='ID события во внешнем календаре')),
                ('organizer', models.ForeignKey(help_text='Укажите пользователя, организатора события', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('previous_event_id', models.ForeignKey(blank=True, help_text='Связь с предыдущим событием при переносе (перенос = archived текущего события + planned новое)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_events', to='calendar_engine.calendarevent', verbose_name='Предыдущее событие при переносе')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, help_text='Для корректного применения правила повторения в календаре пользователя', null=True, verbose_name='Часовой пояс')),
                ('rule_start', models.DateField(help_text='Укажите дату старта правила повторения', verbose_name='Дата старта правила повторения')),
                ('rule_end', models.DateField(blank=True, help_text='Укажите дату окончания правила повторения', null=True, verbose_name='Дата окончания правила повторения')),
                ('count_recurrences', models.PositiveSmallIntegerField(blank=True, help_text='Укажите максимальное количество повторений', null=True, verbose_name='Максимальное количество повторений')),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], help_text='Укажите периодичность повторения (monthly / weekly / daily)', max_length=32, null=True, verbose_name='Периодичность повторения')),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='Интервал повторения (1 - каждую неделю, 2 - через неделю)', verbose_name='Интервал повторения')),
                ('weekdays_recurrences', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), blank=True, help_text='Укажите дни недели для повторения', null=True, size=None, verbose_name='Дни недели для повторений')),
                ('is_active', models.BooleanField(default=True, help_text='Флаг действия правила повторения', verbose_name='Признак действия правила повторения')),
                ('event', models.ForeignKey(help_text='Укажите событие для повторения', on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='calendar_engine.calendarevent', verbose_name='Событие для повторения')),
                ('owner', models.ForeignKey(help_text='Укажите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='recurrences_rules', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Правило повторения события',
                'verbose_name_plural': 'Правила повторений событий',
                'ordering': ['pk', 'owner', 'rule_start'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(help_text='Укажите начало события', verbose_name='Начало события')),
                ('end_datetime', models.DateTimeField(help_text='Укажите окончание события', verbose_name='Окончание события')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('started', 'Начато'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('archived', 'Архивировано')], default='planned', help_text='Укажите статус слота', max_length=32, verbose_name='Статус слота')),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, help_text='Для корректного отображения слотов в календаре пользователя', null=True, verbose_name='Часовой пояс')),
                ('meeting_url', models.URLField(blank=True, help_text='Укажите ссылку на видео-комнату', null=True, verbose_name='Ссылка на видео-комнату')),
                ('comment', models.TextField(blank=True, help_text='Укажите комментарий', null=True, verbose_name='Комментарий')),
                ('slot_index', models.PositiveSmallIntegerField(default=1, help_text='Укажите порядок слота внутри события', verbose_name='Порядок слота внутри события')),
                ('event', models.ForeignKey(help_text='Укажите слот для события', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='calendar_engine.calendarevent', verbose_name='Слот для события')),
                ('owner', models.ForeignKey(help_text='Укажите владельца слота', on_delete=django.db.models.deletion.CASCADE, related_name='owned_slots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец слота')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
                'ordering': ['start_datetime', 'event', 'slot_index'],
            },
        ),
        migrations.CreateModel(
            name='SlotParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время присоединения')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время выхода')),
                ('role', models.CharField(choices=[('organizer', 'Организатор'), ('participant', 'Участник'), ('speaker', 'Выступающий'), ('moderator', 'Модератор'), ('observer', 'Наблюдатель')], default='participant', help_text='Укажите роль участника в слоте событии', max_length=32, verbose_name='Роль участника в слоте')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('joined', 'Присоединился'), ('left_early', 'Покинул раньше'), ('attended', 'Посещено'), ('missed', 'Пропущено')], default='planned', help_text='Укажите статус участника в слоте события', max_length=32, verbose_name='Статус участника в слоте события')),
                ('user', models.ForeignKey(help_text='Укажите участника слота события', on_delete=django.db.models.deletion.CASCADE, related_name='slot_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник слота события')),
                ('slot', models.ForeignKey(help_text='Укажите слот события', on_delete=django.db.models.deletion.CASCADE, related_name='slot_participants', to='calendar_engine.timeslot', verbose_name='Слот события')),
            ],
            options={
                'verbose_name': 'Участник слота в событии',
                'verbose_name_plural': 'Участники слота в событии',
                'ordering': ['pk', 'slot__start_datetime', 'slot', 'user'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время присоединения')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время выхода')),
                ('role', models.CharField(choices=[('organizer', 'Организатор'), ('participant', 'Участник'), ('moderator', 'Модератор'), ('observer', 'Наблюдатель')], default='participant', help_text='Укажите роль участника в событии', max_length=32, verbose_name='Роль участника в событии')),
                ('status', models.CharField(choices=[('invited', 'Приглашен'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('left', 'Покинул')], default='invited', help_text='Укажите статус участника в событии', max_length=32, verbose_name='Статус участника в событии')),
                ('event', models.ForeignKey(help_text='Укажите событие', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calendar_engine.calendarevent', verbose_name='Событие')),
                ('user', models.ForeignKey(help_text='Укажите участника события', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник события')),
            ],
            options={
                'verbose_name': 'Участник события',
                'verbose_name_plural': 'Участники события',
                'ordering': ['pk', 'event', 'user'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='calendar_en_start_d_0076d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['planned', 'started'])), expressions=[(models.F('owner'), '='), (models.Func(models.F('start_datetime'), models.F('end_datetime'), function='tstzrange'), '&&')], name='prevent_slot_overlap_per_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('event', 'slot_index')},
        ),
        migrations.AlterUniqueTogether(
            name='slotparticipant',
            unique_together={('slot', 'user')},
        ),
    ]
