# Generated by Django 5.2.7 on 2026-01-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланировано'), ('started', 'Начато'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('archived', 'Архивировано')], default='draft', help_text='Укажите статус события', max_length=32, verbose_name='Статус события'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('started', 'Начато'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('archived', 'Архивировано')], default='planned', help_text='Укажите статус слота', max_length=32, verbose_name='Статус слота'),
        ),
    ]
