# Generated by Django 5.2.7 on 2026-01-09 12:42

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0002_alter_calendarevent_status_alter_timeslot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityexception',
            options={'ordering': ['pk', 'creator', 'exception_start'], 'verbose_name': 'Исключение из правил доступности', 'verbose_name_plural': 'Исключения из правил доступности'},
        ),
        migrations.AlterModelOptions(
            name='availabilityrule',
            options={'ordering': ['pk', 'creator', 'rule_start'], 'verbose_name': 'Правило доступности специалиста', 'verbose_name_plural': 'Правила доступности специалиста'},
        ),
        migrations.AlterModelOptions(
            name='recurrencerule',
            options={'ordering': ['pk', 'creator', 'rule_start'], 'verbose_name': 'Правило повторения события', 'verbose_name_plural': 'Правила повторений событий'},
        ),
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='prevent_slot_overlap_per_owner',
        ),
        migrations.RenameField(
            model_name='availabilityexception',
            old_name='owner',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='availabilityrule',
            old_name='owner',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='organizer',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='owner',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='owner',
            new_name='creator',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['planned', 'started'])), expressions=[(models.F('creator'), '='), (models.Func(models.F('start_datetime'), models.F('end_datetime'), function='tstzrange'), '&&')], name='prevent_slot_overlap_per_creator'),
        ),
    ]
