# Generated by Django 5.2.7 on 2026-01-10 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0003_alter_availabilityexception_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityexception',
            options={'ordering': ['pk', 'creator', 'exception_date_start', 'exception_start_time'], 'verbose_name': 'Исключение из правил доступности', 'verbose_name_plural': 'Исключения из правил доступности'},
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='exception_end',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='exception_start',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='global_availability',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='start_time',
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='exception_date_end',
            field=models.DateField(default=django.utils.timezone.now, help_text='Укажите дату окончания действия исключения', verbose_name='Дата окончания действия исключения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='exception_date_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Укажите дату старта действия исключения', verbose_name='Дата старта действия исключения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='exception_end_time',
            field=models.TimeField(blank=True, help_text='Укажите время окончания действия исключения', null=True, verbose_name='Время окончания действия исключения'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='exception_start_time',
            field=models.TimeField(blank=True, help_text='Укажите время начала действия исключения', null=True, verbose_name='Время начала действия исключения'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='exception_type',
            field=models.CharField(choices=[('unavailable', 'Полностью недоступен'), ('override', 'Частичное переопределение')], default='unavailable', help_text='Укажите тип исключения (полностью недоступен или изменение текущего рабочего правила', verbose_name='Тип исключения'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Флаг действия исключения', verbose_name='Признак действия исключения'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_break_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Укажите перерыв между сессиями согласно исключения', null=True, verbose_name='Перерыв между сессиями согласно исключения'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_end_time',
            field=models.TimeField(blank=True, help_text='Укажите новое окончание рабочего дня согласно исключения', null=True, verbose_name='Новое окончание рабочего дня согласно исключения'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_slot_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=60, help_text='Укажите продолжительность 1 слота согласно исключения', null=True, verbose_name='Продолжительность 1 слота согласно исключения'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_start_time',
            field=models.TimeField(blank=True, help_text='Укажите новое начало рабочего дня согласно исключения', null=True, verbose_name='Новое начало рабочего дня согласно исключения'),
        ),
    ]
