# Generated by Django 5.2.7 on 2026-01-12 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0004_alter_availabilityexception_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityexception',
            name='reason',
            field=models.CharField(choices=[('day_off', 'Выходной'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный')], default=django.utils.timezone.now, help_text='Укажите причину исключения', max_length=32, verbose_name='Причина исключения'),
            preserve_default=False,
        ),
    ]
