# Generated by Django 5.2.7 on 2026-01-23 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0005_alter_availabilityexception_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityexception',
            options={'ordering': ['pk', 'creator', 'exception_start'], 'verbose_name': 'Исключение из правил доступности', 'verbose_name_plural': 'Исключения из правил доступности'},
        ),
        migrations.AlterModelOptions(
            name='availabilityrule',
            options={'ordering': ['pk', 'creator', 'rule_start'], 'verbose_name': 'Правило доступности', 'verbose_name_plural': 'Правила доступности'},
        ),
        migrations.RenameField(
            model_name='availabilityexception',
            old_name='exception_date_end',
            new_name='exception_end',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='exception_date_start',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='exception_end_time',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='exception_start_time',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='override_break_minutes',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='override_end_time',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='override_slot_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='override_start_time',
        ),
        migrations.RemoveField(
            model_name='availabilityrule',
            name='break_minutes',
        ),
        migrations.RemoveField(
            model_name='availabilityrule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availabilityrule',
            name='slot_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='availabilityrule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='exception_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Укажите дату начала действия исключения', verbose_name='Дата начала действия исключения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabilityrule',
            name='break_between_sessions',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Укажите перерыв между сессиями (минуты)', null=True, verbose_name='Перерыв между сессиями (минуты)'),
        ),
        migrations.AddField(
            model_name='availabilityrule',
            name='slot_duration',
            field=models.PositiveSmallIntegerField(default=60, help_text='Укажите продолжительность 1 слота (минуты)', verbose_name='Продолжительность 1 слота (минуты)'),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='rule_end',
            field=models.DateField(blank=True, help_text='Укажите дату окончания действия правила', null=True, verbose_name='Дата окончания действия правила'),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='rule_start',
            field=models.DateField(help_text='Укажите дату начала действия правила', verbose_name='Дата начала действия правила'),
        ),
        migrations.CreateModel(
            name='AvailabilityExceptionTimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('override_start_time', models.TimeField(blank=True, help_text='Укажите новое начало временного окна согласно исключения', null=True, verbose_name='Новое начало временного окна согласно исключения')),
                ('override_end_time', models.TimeField(blank=True, help_text='Укажите новое окончание временного окна согласно исключения', null=True, verbose_name='Новое окончание временного окна согласно исключения')),
                ('override_slot_duration', models.PositiveSmallIntegerField(blank=True, default=60, help_text='Укажите продолжительность 1 слота согласно исключения (минуты)', null=True, verbose_name='Продолжительность 1 слота согласно исключения (минуты)')),
                ('override_break_between_sessions', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Укажите перерыв между сессиями согласно исключения (минуты)', null=True, verbose_name='Перерыв между сессиями согласно исключения (минуты)')),
                ('exception', models.ForeignKey(help_text='Укажите исключение', on_delete=django.db.models.deletion.CASCADE, related_name='time_windows', to='calendar_engine.availabilityexception', verbose_name='Исключение')),
            ],
            options={
                'verbose_name': 'Переопределенное временное окно доступности',
                'verbose_name_plural': 'Переопределенные временные окна доступности',
                'ordering': ['exception', 'override_start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRuleTimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_time', models.TimeField(help_text='Укажите начало временного окна', verbose_name='Начало временного окна')),
                ('end_time', models.TimeField(help_text='Укажите окончание временного окна', verbose_name='Окончание временного окна')),
                ('rule', models.ForeignKey(help_text='Укажите рабочее расписание', on_delete=django.db.models.deletion.CASCADE, related_name='time_windows', to='calendar_engine.availabilityrule', verbose_name='Рабочее расписание')),
            ],
            options={
                'verbose_name': 'Временное окно доступности',
                'verbose_name_plural': 'Временные окна доступности',
                'ordering': ['rule', 'start_time'],
            },
        ),
    ]
