# Generated by Django 5.2.7 on 2026-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0006_alter_availabilityexception_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityexceptiontimewindow',
            name='override_slot_duration',
            field=models.PositiveSmallIntegerField(blank=True, default=60, help_text='Укажите продолжительность 1 сессии согласно исключения (минуты)', null=True, verbose_name='Продолжительность 1 сессии согласно исключения (минуты)'),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='slot_duration',
            field=models.PositiveSmallIntegerField(default=60, help_text='Укажите продолжительность 1 сессии (минуты)', verbose_name='Продолжительность 1 сессии (минуты)'),
        ),
    ]
