# Generated by Django 5.2.7 on 2026-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0007_alter_availabilityexceptiontimewindow_override_slot_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityexceptiontimewindow',
            name='override_break_between_sessions',
        ),
        migrations.RemoveField(
            model_name='availabilityexceptiontimewindow',
            name='override_slot_duration',
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_break_between_sessions',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Укажите перерыв между сессиями согласно исключения (минуты)', null=True, verbose_name='Перерыв между сессиями согласно исключения (минуты)'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_slot_duration',
            field=models.PositiveSmallIntegerField(blank=True, default=60, help_text='Укажите продолжительность 1 сессии согласно исключения (минуты)', null=True, verbose_name='Продолжительность 1 сессии согласно исключения (минуты)'),
        ),
    ]
