# Generated by Django 5.2.7 on 2026-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0008_remove_availabilityexceptiontimewindow_override_break_between_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityexception',
            name='reason',
            field=models.CharField(choices=[('day_off', 'Выходной'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('short_day', 'Сокращенный день'), ('other', 'Другое')], help_text='Укажите причину исключения', max_length=32, verbose_name='Причина исключения'),
        ),
    ]
