# Generated by Django 5.2.7 on 2026-03-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0009_alter_availabilityexception_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='previous_event_id',
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_minimum_booking_notice_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Укажите новое минимальное количество часов до старта слота для записи на период исключения', null=True, verbose_name='Новое минимальное количество часов до ближайшего доступного слота для записи'),
        ),
        migrations.AddField(
            model_name='availabilityrule',
            name='minimum_booking_notice_hours',
            field=models.PositiveSmallIntegerField(default=1, help_text='Укажите, за сколько минимум часов до начала слота клиенту можно показывать слот для записи', verbose_name='Минимальное количество часов до ближайшего доступного слота для записи'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='cancel_reason_type',
            field=models.CharField(blank=True, choices=[('cancelled_by_user', 'Отменено пользователем'), ('rescheduled', 'Перенесено'), ('cancelled_by_admin', 'Отменено администратором')], help_text='Укажите тип причины отмены события (например: отменено пользователем, перенос, отменено админом)', max_length=32, null=True, verbose_name='Тип причины отмены события'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='previous_event',
            field=models.ForeignKey(blank=True, help_text='Связь с предыдущим событием при переносе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_events', to='calendar_engine.calendarevent', verbose_name='Предыдущее событие при переносе'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Укажите текстовое пояснение причины отмены события', null=True, verbose_name='Причина отмены события'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('session_individual', 'Индивидуальная сессия'), ('session_couple', 'Парная сессия'), ('session_group', 'Групповая сессия'), ('blocked_time', 'Блокировка времени'), ('external_busy', 'Внешняя занятость')], default='session_individual', help_text='Укажите тип события', max_length=32, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланировано'), ('started', 'Начато'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='draft', help_text='Укажите статус события', max_length=32, verbose_name='Статус события'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('invited', 'Приглашен'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('removed', 'Удален')], default='invited', help_text='Укажите статус участника в событии', max_length=32, verbose_name='Статус участника в событии'),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('joined', 'Присоединился'), ('left_early', 'Покинул раньше'), ('attended', 'Посещено'), ('missed', 'Пропущено'), ('cancelled', 'Отменено')], default='planned', help_text='Укажите статус участника в слоте события', max_length=32, verbose_name='Статус участника в слоте события'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('started', 'Начато'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', help_text='Укажите статус слота', max_length=32, verbose_name='Статус слота'),
        ),
    ]
