# Generated by Django 5.2.7 on 2026-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0010_remove_calendarevent_previous_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityexception',
            name='override_slot_duration',
        ),
        migrations.RemoveField(
            model_name='availabilityrule',
            name='slot_duration',
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_session_duration_couple',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Укажите продолжительность 1 парной сессии согласно исключения (минуты)', null=True, verbose_name='Продолжительность 1 парной сессии согласно исключения (минуты)'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='override_session_duration_individual',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Укажите продолжительность 1 индивидуальной сессии согласно исключения (минуты)', null=True, verbose_name='Продолжительность 1 индивидуальной сессии согласно исключения (минуты)'),
        ),
        migrations.AddField(
            model_name='availabilityrule',
            name='session_duration_couple',
            field=models.PositiveSmallIntegerField(default=90, help_text='Укажите продолжительность 1 парной сессии (минуты)', verbose_name='Продолжительность 1 парной сессии (минуты)'),
        ),
        migrations.AddField(
            model_name='availabilityrule',
            name='session_duration_individual',
            field=models.PositiveSmallIntegerField(default=50, help_text='Укажите продолжительность 1 индивидуальной сессии (минуты)', verbose_name='Продолжительность 1 индивидуальной сессии (минуты)'),
        ),
        migrations.AlterField(
            model_name='availabilityexception',
            name='override_break_between_sessions',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Укажите перерыв между сессиями согласно исключения (минуты)', null=True, verbose_name='Перерыв между сессиями согласно исключения (минуты)'),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='break_between_sessions',
            field=models.PositiveSmallIntegerField(blank=True, default=10, help_text='Укажите перерыв между сессиями (минуты)', null=True, verbose_name='Перерыв между сессиями (минуты)'),
        ),
    ]
