# Generated by Django 5.2.7 on 2026-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0011_remove_availabilityexception_override_slot_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='cancel_reason_type',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Укажите текстовое пояснение причины отмены конкретной встречи', null=True, verbose_name='Причина отмены слота'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='cancel_reason_type',
            field=models.CharField(blank=True, choices=[('cancelled_by_user', 'Отменено пользователем'), ('rescheduled', 'Перенесено'), ('cancelled_by_admin', 'Отменено администратором')], help_text='Укажите тип причины отмены конкретной встречи внутри события', max_length=32, null=True, verbose_name='Тип причины отмены слота'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='meeting_resume',
            field=models.TextField(blank=True, help_text='Укажите краткий протокол, выводы или результаты проведенной встречи', null=True, verbose_name='Итоги встречи'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(choices=[('internal', 'Сервис ОПОРА'), ('google', 'Google календарь'), ('apple', 'Apple календарь'), ('outlook', 'Outlook календарь')], default='internal', help_text='Укажите источник события', max_length=32, verbose_name='Источник события'),
        ),
    ]
