# Generated by Django 5.2.7 on 2026-03-25 23:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0012_remove_calendarevent_cancel_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='comment',
        ),
        migrations.CreateModel(
            name='TimeSlotComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Укажите текст сообщения участника встречи', verbose_name='Текст сообщения')),
                ('is_rewrited', models.BooleanField(default=False, help_text='Флаг нужен, чтобы на UI показывать, что автор уже менял текст сообщения', verbose_name='Сообщение отредактировано')),
                ('creator', models.ForeignKey(help_text='Укажите пользователя, который оставил сообщение внутри встречи', on_delete=django.db.models.deletion.CASCADE, related_name='authored_slot_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
                ('slot', models.ForeignKey(help_text='Укажите встречу, к которой относится сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='calendar_engine.timeslot', verbose_name='Слот встречи')),
            ],
            options={
                'verbose_name': 'Сообщение встречи',
                'verbose_name_plural': 'Сообщения встреч',
                'ordering': ['-created_at'],
            },
        ),
    ]
